### ISSUE TITLE
Errors while running testAlign.py

### ISSUE THREAD

**Issue by vishuv** [ma-sultan/monolingual-word-aligner#1]
Any clue on how to fix this?
I have done a fresh install following the steps given in Readme and got the following error when ran testAlign.py

```
Traceback (most recent call last):
  File "testAlign.py", line 7, in <module>
    alignments = align(sentence1, sentence2)
  File "/home/saketh/stanford-corenlp-python/monolingual-word-aligner/aligner.py", line 1567, in align
    myWordAlignments = alignWords(sentence1LemmasAndPosTags, sentence2LemmasAndPosTags, sentence1ParseResult, sentence2ParseResult)
  File "/home/saketh/stanford-corenlp-python/monolingual-word-aligner/aligner.py", line 1198, in alignWords
    sourceDParse = dependencyParseAndPutOffsets(sourceParseResult)
  File "/home/saketh/stanford-corenlp-python/monolingual-word-aligner/coreNlpUtil.py", line 191, in dependencyParseAndPutOffsets
    left = item[1][0:item[1].rindex("-")]
ValueError: substring not found
```

**Comment by ma-sultan** [comment]
Does it happen on the sentence pair already in testAlign.py, or on a new
pair? Could you give me the content of the variable 'item' in the former
case? (Just 'print item' in the beginning of the loop and send me the full
output.) In the latter case, please send me the pair.

As a general sort of suggestion, rfind() is an alternative to rindex() that
returns -1 in case the substring is not found (rather than raising an
exception).

Arafat

**Comment by vishuv** [comment]
Thanks for the help Arafat. I think I did not change line 100 of "corenlp.py" appropriately. Sorry for the trouble.
