### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by hsvgbkhgbv** [ma-sultan/monolingual-word-aligner#4]
This is the report:

Traceback (most recent call last):
  File "/home/jianhong/Final_Year_Project/DLSbased_method.py", line 59, in <module>
    extract_and_produce_data(load_dir, save_dir)
  File "/home/jianhong/Final_Year_Project/DLSbased_method.py", line 29, in extract_and_produce_data
    alignments = align(sentence_1, sentence_2)
  File "/home/jianhong/Final_Year_Project/aligner.py", line 1542, in align
    sentence2ParseResult = parseText(sentence2)
  File "/home/jianhong/Final_Year_Project/coreNlpUtil.py", line 24, in parseText
    parseResult = nlp.parse(sentences)
  File "/home/jianhong/Final_Year_Project/coreNlpUtil.py", line 18, in parse
    return json.loads(self.server.parse(text))
  File "/home/jianhong/Final_Year_Project/jsonrpc.py", line 934, in **call**
    return self.__req(self.__name, args, kwargs)
  File "/home/jianhong/Final_Year_Project/jsonrpc.py", line 907, in __req
    resp = self.__data_serializer.loads_response( resp_str )
  File "/home/jianhong/Final_Year_Project/jsonrpc.py", line 626, in loads_response
    raise RPCInternalError(error_data)
jsonrpc.RPCInternalError: <RPCFault -32603: 'Internal error.' (None)>

**Comment by basmahassan** [comment]
Me too got this error specially when tried to run the aligner on SemEval-STS 2016 postediting dataset (STS2016.input.postediting.txt), and i don't know how it can be fixed? 
![screenshot from 2016-07-03 01 27 42](https://cloud.githubusercontent.com/assets/5060231/16700086/5931a6da-4558-11e6-89be-01cd792fe273.png)

**Comment by hsvgbkhgbv** [comment]
I think it's better to let the author resolve this problem.

**Comment by dhanasution** [comment]
Me too got this error. how it can be fixed?

**Comment by tkngoutham** [comment]
Hi People you have to start corenlp before running these modules.
https://github.com/dasmith/stanford-corenlp-python
